#ifndef LIVEPATCHLISTSELECTEDINDEXCHANGED_H_INCLUDED
#define LIVEPATCHLISTSELECTEDINDEXCHANGED_H_INCLUDED


#include "../../Defines.h"


EVENT(LivePatchListSelectedIndexChanged, (int value))


#endif  // LIVEPATCHLISTSELECTEDINDEXCHANGED_H_INCLUDED
