#ifndef LIVEPATCHEDITORMODECLICKED_H_INCLUDED
#define LIVEPATCHEDITORMODECLICKED_H_INCLUDED


#include "../../Defines.h"


EVENT(LivePatchEditorModeClicked, ())


#endif  // LIVEPATCHEDITORMODECLICKED_H_INCLUDED
