#ifndef BANDPASSPARAMETERCHANGED_H_INCLUDED
#define BANDPASSPARAMETERCHANGED_H_INCLUDED


#include "../../Defines.h"


EVENT(BandPassParameterChanged, (bool value))




#endif  // BANDPASSPARAMETERCHANGED_H_INCLUDED
