#ifndef HIGHPASSPARAMETERCHANGED_H_INCLUDED
#define HIGHPASSPARAMETERCHANGED_H_INCLUDED


#include "../../Defines.h"


EVENT(HighPassParameterChanged, (bool value))




#endif  // HIGHPASSPARAMETERCHANGED_H_INCLUDED
